files: pablog_api/

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: fix-byte-order-marker
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: mixed-line-ending
        args: [--fix=auto]
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]

  - repo: local
    hooks:
      - id: lint-fix
        name: lint-fix
        entry: bash -c 'make lint-fix'
        language: system

  - repo: local
    hooks:
      - id: mypy-check
        name: mypy-check
        entry: bash -c 'make mypy'
        language: system

  - repo: local
    hooks:
      - id: validate-gunicorn-config
        name: validate-gunicorn-config
        entry: bash -c 'make check-server-cfg'
        language: system

  - repo: local
    hooks:
      - id: check-security-issues
        name: check-security-issues
        entry: bash -c 'make bandit'
        language: system

  - repo: local
    hooks:
      - id: check-if-migrations-generated
        name: check-if-migrations-generated
        entry: bash -c 'make check-migrations'
        language: system
