"""

Revision ID: e782c3b48987
Revises: 
Create Date: 2024-06-29 13:25:11.071658

"""
from collections.abc import Sequence


# revision identifiers, used by Alembic.
revision: str = 'e782c3b48987'
down_revision: str | None = None
branch_labels: str | (Sequence[str] | None) = None
depends_on: str | (Sequence[str] | None) = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
