version: "3"


services:
  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/site.conf:/etc/nginx/conf.d/default.conf
      - ../logs/nginx/:/var/log/nginx/
      - /tmp/gunicorn.sock:/tmp/gunicorn.sock
  api:
    build:
      context: ../
      target: prod
    restart: unless-stopped
    env_file:
      - .env.server
    depends_on:
      - nginx
    volumes:
      - /tmp/gunicorn.sock:/tmp/gunicorn.sock
