version: "3"


services:

  test:
    build:
      context: ../
      target: test
    command: integration
    env_file:
      - ../tests/integration/.env.test
    depends_on:
      master_db:
        condition: service_healthy
      cache:
        condition: service_healthy

  master_db:
    image: postgres:16.2
    command: -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_DB: pablog
      POSTGRES_USER: pablog
      POSTGRES_PASSWORD: pablog
    volumes:
      - ./db/master.conf:/etc/postgresql/postgresql.conf
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'" ]
      interval: 5s
      timeout: 10s
      retries: 5

  cache:
    image: redis:7.2.5
    entrypoint: [ "redis-server", "/etc/redis/redis.conf" ]
    volumes:
      - ./cache/redis-test.conf:/etc/redis/redis.conf
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 10s
      retries: 10


volumes:
  app_runtime: