version: "3"


services:
  master_db:
    image: postgres:16.2
    command: -c config_file=/etc/postgresql/postgresql.conf
    container_name: pablog-masterdb
    restart: unless-stopped
    env_file:
      - ./db/.env.db
    ports:
      - "5432:5432"
    volumes:
      - archive_db_volume:/var/lib/postgresql/db/wal_archive/
      - master_db_volume:/var/lib/postgresql/data
      - ./db/master.conf:/etc/postgresql/postgresql.conf
      - ../logs/postgresql/:/var/log/postgresql/
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 5s
      timeout: 10s
      retries: 5


volumes:
  master_db_volume:
  archive_db_volume:


networks:
  db:
