name: python tests


on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11-slim", "3.12-slim"]
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: |
          echo ${{ matrix.python }} >> $PYTHON_VERSION
          make unit-test
