name: python validation


on:
  push:
    paths:
      - pablog_api/**
      - tests/**


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [ "3.11.9", "3.12.4" ]
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: ${{matrix.python}}

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Validate that lock file is consistent with pyproject.toml
        run: make check-lock

      - name: Install dependencies
        run: poetry install --with dev

      - name: Run linter
        run: make lint

      - name: Run mypy
        run: make mypy

      - name: Check gunicorn config
        run: make check-server-cfg

      - name: Check security issues
        run: make bandit
