name: python tests


on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.11-slim", "3.12-slim"]
    env:
      PYTHON_VERSION: ${{matrix.python}}
    steps:
      - uses: actions/checkout@v2

      - name: Run unit tests
        run: make unit-test

#      Run integration tests only on release as tests quite heavy
#      - name: Run integration tests
#        run: make integration-test
