name: pablog service ci


on:
  push:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.6

      - name: Install and configure poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.6.1
          virtualenvs-create: true
          virtualenvs-in-project: true

      - name: Install dependencies
        run: |
          poetry install --with dev

      - name: Run linter
        run: |
          poetry run ruff check .

      - name: Run mypy
        run: |
          poetry run mypy

      - name: Check gunicorn config
        run: |
          set -a
          source .env.example
          poetry run gunicorn --config pablog_api/gunicorn_conf.py --check-config pablog_api.api.server:app

      - name: Check security issues
        run: |
          poetry run bandit -r pablog_api/

      - name: Check Dockerfile issues
        run: |
          docker pull hadolint/hadolint
          docker run --rm -i hadolint/hadolint hadolint --ignore DL3008 --ignore DL4006 - < Dockerfile
