name: extra tools validation


on:
  push:
    paths:
      - Dockerfile
      - compose/nginx/**


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Check Dockerfile issues
        run: make check-docker

      - name: Validate nginx
        run: make check-nginx
